<a href="https://colab.research.google.com/github/MattEntornos/matematicas/blob/main/algebra/practica_algebra_matthew.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Práctica 3. Álgebra
* Para aprender sobre Python vea la playlist [Python para Matemáticas](https://www.youtube.com/playlist?list=PL8gpDXwO-9l4HkDJ9QhB4H-cOiT0BYGau)
* Para obtener ideas y vídeos para la resolución de la práctica vea los archivos siguientes: [Ideas](https://github.com/financieras/math/tree/main/ideas)

## Práctica 3.1
**Determinante en Excel**  

* Cree un fichero en Excel de nombre algebra.xlsm.
* La extensión **xlsm** corresponde a los archivos de Excel habilitados para macros.
* Utilice la Hoja 1 para hacer la Práctica 3.1.
* Se pide:
 1. Cree una matriz cuadrada de dimensión 5×5, formada por números aleatorios enteros entre -9 y +9.
 2. Calcule el determinante de esta matriz
 3. Cree un programa en **VBA** que busque una matriz de este tipo cuyo determinante sea cero.
 4. Copie la matriz encontrada y péguela debajo con "pegado especial valores" para que no varíe su contenido al efectuar el recálculo manual de la hoja.

## Práctica 3.2
**Matriz inversa en Excel**  

* Use el mismo archivo de Excel con extensión **xlsm** del caso anterior. 
* Utilice la Hoja 2 para hacer la Práctica 3.2.
* Se pide:
 1. Crea la matriz $A$ que es una matriz cuadrada de dimensiones 5×5 usando números aleatorios enteros entre -9 y +9, excepto cero
 2. Calcule su determinante
 3. Calcule su transpuesta usando la función ```TRANSPONER```
 4. Calcule su matriz inversa $A^{-1}$
 5. Multiplique la matriz $A$ por su inversa $A^{-1}$ y compruebe que el producto es la matriz identidad.
 $$AA^{-1}=I$$

## Práctica 3.3
**Resolución de sistemas lineales en Excel**  

* Use el mismo archivo de Excel con extensión **xlsm** del caso anterior. 
* Utilice la Hoja 3 para hacer la Práctica 3.3.
* Se pide:
 1. Cree un sistema de 5 ecuaciones con 5 incógnitas con **solución única**.
 2. Una de las ecuaciones será: $\quad x_1+2x_2-x_3+x_4-3x_5=6$
 3. Muestre las ecuaciones del sistema usando el [editor de ecuaciones](https://support.microsoft.com/es-es/office/editor-de-ecuaciones-6eac7d71-3c74-437b-80d3-c7dea24fdf3f) de Excel. $\quad Ax=b$
 4. Monte la matriz $A$ del sistema de ecuaciones y la matriz $b$ con los términos independientes. Muestre ambas matrices.
 5. Calcule la matriz inversa $A^{-1}$
 6. Resuelva el sistema lineal de ecuaciones con este método: $\quad Ax=b \quad \Longrightarrow \quad x=A^{-1}b$
 7. Compruebe si el resultado obtenido es la solución del sistema de ecuaciones. Justifique esa comprobación.

## Práctica 3.4
**Matriz inversa en Python**  

Desarrolla un código en Python que al ejecutarse consiga los siguientes apartados.  
1. Crea una matriz cuadrada de dimensiones 3×3 usando números aleatorios enteros entre -9 y +9, excepto cero
2. Buscar un caso donde el determinante sea igual a 1
3. Si el determinante es 1 imprime la matriz y su determinante
4. Calcula e imprime su transpuesta
5. Calcula e imprime su matriz inversa
6. Multiplica la matriz creada por su inversa y comprueba que el producto es la matriz identidad.
7. Calcula cuantos segundos ha tardado en realizarse el proceso.

In [ ]:
from random import randint, seed, choice
import numpy as np
from time import process_time


def aleatorio():
  seed() 
  numero = randint(1,9) * choice([1,-1]) 
  return numero

t1 = process_time()

while True:
    
    m = np.array([[aleatorio(),aleatorio(),aleatorio()],[aleatorio(),aleatorio(),aleatorio()],[aleatorio(),aleatorio(),aleatorio()]])
    determ = np.linalg.det(m)
    redondeadoDeter = round(determ)

    if redondeadoDeter == 1:
        print("  Matriz A:")
        print()
        print(m)
        print()
        print("Su transpuesta es:")
        print()
        transpuesta = np.transpose(m)
        print(transpuesta)
        print()
        print("Su inversa es:")
        print()
        inversa = np.linalg.inv(m)
        print(inversa)
        print()

        print("Matriz Identidad:")
        print()
        identidad = np.dot(m, inversa)   
        print(identidad)
        print()

        print("Matriz Identidad con valores enteros:")
        identidad = np.around(identidad, 6)
        print()
        print(identidad.astype(int))
        
        print()
        
        break

print(f"El determinante de la matriz A es {redondeadoDeter}")
t2 = process_time()
print(f"El proceso ha tardado {t2-t1} segundos.")


In [ ]:
# UNA PRUEBA FALLIDA 
"""from random import randint, seed, choice   #Importo las librerias que voy a utilizar
import numpy as np

seed() #Inicializo el generador de numeros aleatorios
m = [] #Inicializo mi matriz


def matriz():

  for i in range(3):
        fila = []
        for j in range(3):
            aleatorio = randint(1,9) * choice([1,-1])   #Genero un numero aleatorio para cada hueco en la fila 
            fila.append(aleatorio)    #La situo en la fila
        m.append(fila)    #Y cuando ya haya completado la fila con numeros aleatorios excepto el 0, la pego en mi matriz
  determ = round(np.linalg.det(m))

  return determ, m

while True:

    d, matri = matriz()

    if d == 1:
        print(matri)
        break

print(f"El determinante de la matriz es {d}")"""



## Práctica 3.5
**Resolución de sistemas lineales en Python**  

1. Cree un sistema de 4 ecuaciones con 4 incógnitas con **solución única**.
2. La solución del sistema es: $\; \begin{pmatrix}x_1, x_2, x_3, x_4\end{pmatrix} = \begin{pmatrix} 3, 4, 5, 2\end{pmatrix}$  
3. Una de las ecuaciones del sistema es: $\enspace x_1+3x_2-x_3-2x_4=6$  
4. El vector $b$ de términos independientes es: $\enspace b=\begin{pmatrix}6, 3, 5, 7\end{pmatrix}$  
5. Usando números aleatorios elija los coeficientes que faltan de la matriz $A$ del sistema de ecuaciones.
  - Los coeficientes deben ser números enteros entre -5 y +5, excluido el cero.
  - Imprima la matriz $A$.  
6. Calcule e imprima el determinante de $A$.
7. Calcule e imprima la matriz inversa $A^{-1}$  
8. Resuelva el sistema lineal de ecuaciones con este método: $$Ax=b \quad \Longrightarrow \quad x=A^{-1}b$$
9. Compruebe que el resultado obtenido es la solución del sistema de ecuaciones.  
10. Resuelva nuevamente el sistema de ecuaciones usando ```np.linalg.solve```.

In [ ]:
import numpy as np
from random import randint, seed, choice

# MONTO MI MATRIZ DE TERMINOS INDEPENDIENTES

b = np.array([6,3,5,7])


# MONTO MI MATRIZ 4x4 

v = np.array([3,4,5,2])   # Solución de sistema lineal

f1 = [1,3,-1,-2]  # Mi primera ecuacion del sistema dado en el enunciado

def busca(b):
    while True:
        seed() 
        w = np.random.choice(list(range(-5,0)) + list(range(1,6)), 4) # numero aleatorio entre el -5 y 5 sin el 0
        if np.matmul(v, w) == b:   # el producto de los dos vectores debe ser igual al número b
            break
    return w

b2 =  3; 
f2 = busca(b2)
print(f2)

b3 =  5; 
f3 = busca(b3)
print(f3)

b4 =  7; 
f4 = busca(b4)
print(f4)
print()

matriz = [f1, f2, f3, f4]  # formo mi matriz
##########################################################################################

# LA IMPRIMO
print("  Matriz A")
print()
m = np.array(matriz)
print(m)
print()

# CALCULO SU INVERSA
inversa = np.linalg.inv(m)
print(" Su inversa es:")
print()
print(inversa)
print()

# CALCULO SU DETERMINANTE
determ = np.linalg.det(matriz)
redondeadoDeter = round(determ)
print(f" El determinante de la matriz es: {redondeadoDeter}")
print()

# RESUELVO EL SISTEMA CON EL METODO : Ax=b⟹x=A−1b
print(f" La solucion de mi sistema es: {np.dot(inversa, b)}")

# RESUELVO EL SISTEMA CON EL METODO : np.linalg.solve.
solucion = np.linalg.solve(m,b)
print(f" La solucion de mi sistema con solve es: {solucion}")
print()
print(" Podemos comprobar que los dos metodos de soluciones coinciden con la solución del sistema de ecuaciones que me dan el enunciado.")



## Práctica 3.6
**Resolución de sistemas lineales con Octave**  

1. Tome el mismo sistema 4x4 con solución única del ejercicio anterior.
2. Muestra el sistema usando $\LaTeX$
3. Resuélvelo con Octave por dos métodos
4. ¿Ambos métodos dan el mismo resultado?

$\LaTeX$

Sistema lineal 4x4 del ejercicio anterior.

$$\left.
\begin{align*}
1x + 3y -1z -2t &= 6 \\
2x + 2y -1z -3t &= 3 \\
-2x + y + z + t &= 5 \\
5x - 5y + 2z + t &= 7
\end{align*}
\right\}$$


In [ ]:
!apt install octave

In [ ]:
!apt update

In [ ]:
# RESOLVEMOS EL SISTEMA POR EL PRIMER MÉTODO 

%%writefile primero.m

matriz = [1 3 -1 -2; 2 2 -1 -3; -2 1 1 1; 5 -5 2 1]

b = [6; 3; 5; 7]

x = inv(matriz)*b

solucion = rats(x)

In [ ]:
# EJECUTAMOS EL PRIMER METODO
!octave primero.m

In [ ]:
# LO RESOLVEMOS POR EL SEGUNDO METODO

%%writefile segundo.m

G = [1 3 -1 -2 6; 2 2 -1 -3 3; -2 1 1 1 5; 5 -5 2 1 7]

escalonada = rref(G)

solucionDos = rats(escalonada)


In [ ]:
# EJECUTAMOS EL METODO DOS

!octave segundo.m

SOLUCIÓN : Ambos métodos dan el mismo resultado, pero lo muestran de manera diferente.

## Práctica 3.7
**Diagonalización en Python**

* Sea la matriz cuadrada $A$ de orden 4x4

$$A=\left(
\begin{array}{rrrr}
 -1 &-2 &  3 &-1 \\
  0 & 2 &  0 & 0 \\
  0 & 0 &  2 & 0 \\
  0 & 0 &  0 & 1
\end{array}
\right)$$
1. Calcula los **autovalores** y **autovectores**
2. Calcula y muestra:
 - la matriz diagonal $D$
 - la matriz de paso $P$
 - su inversa $P^{-1}$  
3. Comprueba que se cumple que $A^3=PD^3P^{-1}$

In [8]:
import numpy as np
A = np.array([[-1,-2,3,-1], [0,2,0,0], [0,0,2,0], [0,0,0,1]]) #Construimos la matriz
d,P = np.linalg.eig(A) # Calculamos los autovalores y la matriz de paso (autovectores)
D = np.diag(d) # Rellenamos con 0 la matriz diagonal
print("\nD:\n", D) # Matriz diagonal
print("\nP:\n", P) # Matriz de paso
inversa = np.linalg.inv(P) # Calculo la matriz inversa
print("\nInversa:\n", inversa) # La muestro la matriz inversa de la matriz de paso
aCubo = A@A@A # Calculo A al cubo
print("\nAcubo:\n", aCubo) # Muestro A al cubo
Dcubo = D @ D @ D # Calculo la diagonal al cubo
solucion = P @ Dcubo @ inversa # Calculo el resultado de la expresión PD3P−1
print("\nSolución:\n", solucion)
print()
print("COMPROBAMOS QUE LA EXPRESIÓN A3=PD3P−1 SE CUMPLE")


D:
 [[-1.  0.  0.  0.]
 [ 0.  2.  0.  0.]
 [ 0.  0.  2.  0.]
 [ 0.  0.  0.  1.]]

P:
 [[ 1.         -0.5547002   0.70710678 -0.4472136 ]
 [ 0.          0.83205029  0.          0.        ]
 [ 0.          0.          0.70710678  0.        ]
 [ 0.          0.          0.          0.89442719]]

Inversa:
 [[ 1.          0.66666667 -1.          0.5       ]
 [ 0.          1.20185043  0.          0.        ]
 [ 0.          0.          1.41421356  0.        ]
 [ 0.          0.          0.          1.11803399]]

Acubo:
 [[-1 -6  9 -1]
 [ 0  8  0  0]
 [ 0  0  8  0]
 [ 0  0  0  1]]

Solución:
 [[-1. -6.  9. -1.]
 [ 0.  8.  0.  0.]
 [ 0.  0.  8.  0.]
 [ 0.  0.  0.  1.]]

COMPROBAMOS QUE LA EXPRESIÓN A3=PD3P−1 SE CUMPLE


## Práctica 3.8
**Diagonalización con Octave**

Resuelva el ejercicio anterior, pero en esta ocasión utilizando Octave.

In [ ]:
!apt install octave

In [ ]:
!apt update

In [ ]:
%%writefile ejercicio8.m

A = [-1,-2,3,-1; 0,2,0,0; 0,0,2,0; 0,0,0,1]
[P,D]=eig(A)
Dcubo = D^3
Inversa = inv(P)
Acubo = A^3
PxDcuboXPinv = P*Dcubo*P^-1

In [ ]:
!octave ejercicio8.m

In [ ]:
import numpy as np

# CALCULO LOS AUTOVALORES Y AUTOVECTORES DE MI MATRIZ A
A = np.array([[-1,-2,3,-1], [0,2,0,0], [0,0,2,0], [0,0,0,1]]) # Contruyo mi matriz
d,P = np.linalg.eig(A) # Calculamos autovalores y autovectores respectivamente
print("d: ", d) # Mis autovalores los obtengo metidos en un solo vector
D = np.diag(d) # Aqui cambio mis autovalores a matriz diagonal
print("\nD(autovalores):\n", D) # Muestro mis autovalores en matriz diagonal
print("\nP(autovectores):\n", P) # Muestro mi matriz de paso que contiene los autovectores colocados en el mismo orden que los autovalores a los que están asociados en la matriz diagonal
print()

# CALCULAMOS LA INVERSA DE MI MATRIZ DE PASO
inversaP = np.linalg.inv(P)
print("Su inversa es:")
print(inversaP)
print()

#COMPROBAMOS LA SIGUIENTE EXPRESIÓN A3=PD3P−1
aCubo = A@A@A
print("A3:\n")
print(aCubo)
print()
dCubo = D@D@D
segundoMiembro = P@dCubo@inversaP
print("PD3P−1:\n")
print(segundoMiembro)
print()
print("Podemos comprobar que la expresión se cumple.")

## Práctica 3.9
**Libertad para elegir el lugar de trabajo**  
Resolver con **Octave**.

Una empresa de 1.000 empleados permite que sus trabajadores cada día acudan a trabajar a la oficina o que realicen su trabajo desde su casa. Inicialmente el 90% de la plantilla trabajaba en la oficina y solo el 10% lo hacían en casa. Se ha observado que los que un día trabajan en casa tienen una probabilidad del 70% de realizarlo también desde casa al día siguiente, pero que en el restante 30% de los casos acuden a la oficina al día siguiente. Por el contrario, se ha observado que los que un día trabajaron en la oficina al día siguiente vuelven
a la oficina en el 60% de los casos y en el 40% restante van a su casa al día siguiente.
* Determinar qué número de empleados se quedan en casa transcurridos dos días.
* ¿Y a largo plazo cuantos se quedan en casa?

In [9]:
!apt update
!apt install octave

Get:1 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease [3,626 B]
Ign:2 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Hit:3 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:4 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Hit:5 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
Get:6 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:7 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:8 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic InRelease [15.9 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [83.3 kB]
Hit:10 http://ppa.launchpad.net/cran/libgit2/ubuntu bionic InRelease
Hit:11 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic InRelease
Hit:12 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease
Get:14 http://ppa.launchpad.net

In [21]:
%%writefile ejercicionueve.m

empleados = 1000

vectorInicial = [.9; .1] % Declaramos el vector inicial

A = [.6, .3; .4, .7] % Matriz de transicion de probabilidades

[P,D]=eig(A) %  Calculamos la matriz de paso (autovectores) y la matriz diagonal (autovalores)

Dcuadrado = D^2
Acuadrado = A^2

solucionExpresion  = P*Dcuadrado*P^-1

dia2 = Acuadrado * vectorInicial
disp("Empleados en casa el segundo día: "), disp(dia2(2)*empleados)

D10 = D^10
A10 = P*D10*P^-1
dia10 = A10 * vectorInicial
disp("Empleados en casa a largo plazo son: "), disp(dia10(2)*empleados)

Overwriting ejercicionueve.m


In [22]:
!octave ejercicionueve.m

octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
empleados =  1000
vectorInicial =

   0.90000
   0.10000

A =

   0.60000   0.30000
   0.40000   0.70000

P =

  -0.70711  -0.60000
   0.70711  -0.80000

D =

Diagonal Matrix

   0.30000         0
         0   1.00000

Dcuadrado =

Diagonal Matrix

   0.090000          0
          0   1.000000

Acuadrado =

   0.48000   0.39000
   0.52000   0.61000

solucionExpresion =

   0.48000   0.39000
   0.52000   0.61000

dia2 =

   0.47100
   0.52900

Empleados en casa el segundo día: 
 529
D10 =

Diagonal Matrix

   5.9049e-06            0
            0   1.0000e+00

A10 =

   0.42857   0.42857
   0.57143   0.57143

dia10 =

   0.42857
   0.57143

Empleados en casa a largo plazo son: 
 571.43


## Práctica 3.10
**Tendencia del mercado**  
Resolver con **Python**.

En el mercado de automóviles de gran lujo únicamente se disputan la clientela dos marcas (A y B). Las ventas son $M=100.000$ automóviles anuales, no variando esta cifra con el transcurso de los años. La marca A es líder de mercado en este momento con el 75% de las ventas. Sus directivos desean consolidar su liderazgo e incluso aumentarlo, para lo cual todos los años efectúan una fuerte campaña publicitaria con la que consiguen cada año un 40% de los que fueron clientes de su competidora, aunque la empresa A pierde un 20% de sus clientes que se van a la competencia.
* ¿Cuál es la situación a los 3 años?
* ¿Y al cabo de mucho tiempo?

In [30]:
import numpy as np

X0 = np.array([.75, .25]) # Datos iniciales
A = np.array([[.8, .4], [.2 ,.6]]) # Delcaramos la matriz A
X3 = A@A@A@X0
print(f"En tres años: {X3}")

d,P = np.linalg.eig(A) # Calculamos la diagonal(autovalores) y la matriz de paso (autovectores)
D = np.diag(d) # Rellenamos con 0 los demas huecos de la diagonal para construir la matriz
inversaP = np.linalg.inv(P) # Calculamos la inversa de la matriz de paso

A10 = P@(D**10)@inversaP
X10 = A10@X0
print(f"En diez años: {X10}")

X20 = P@(D**20)@inversaP@X0
print(f"En veinte años: {X20}")


En tres años: [0.672 0.328]
En diez años: [0.6666754 0.3333246]
En veinte años: [0.66666667 0.33333333]
